version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          create-repo: false
          dockerfile: Dockerfile
          executor: aws-ecr/default
          platform: linux/amd64
          push-image: true
          repo: cicd-poc
          repo-scan-on-push: true
          tag: ${CIRCLE_SHA1}
      - hold:
          type: approval
          requires:
            - aws-ecr/build-and-push-image
      - aws-ecs/deploy-service-update:
          cluster: cicd_poc
          container-image-name-updates: container=cicd_poc,image-and-tag=cicd_poc:${CIRCLE_SHA1}
          family: cicd_poc_task_definition
          service-name: cicd_poc_service
          requires:
            - hold
